spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  jackson:
    serialization:
      indent_output: true
  mail:
    host: smtp.mxhichina.com
    protocol: smtp
    port: 465
    username: xxx
    password: xxx
  main:
    allow-bean-definition-overriding: true

server:
  port: 8666
