spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    serialization:
      indent_output: true
  mail:
    host: smtp.mxhichina.com
    protocol: smtp
    port: 465
    username: xxx
    password: xxx

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  main:
    allow-bean-definition-overriding: true

#热部署组件
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 8666
  restart:
    enabled: true #是否支持热部署

server:
  port: 8666

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_
